
// Objective-C API for talking to the following Go packages
//
//	greeting
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Xhsbeian_FRAMEWORK_H__
#define __Xhsbeian_FRAMEWORK_H__

#include "Xhsbeian.objc.h"
#include "Universe.objc.h"

#endif
